# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='degree',
            field=models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('mech', 'MECHANICAL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='achievements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='activities',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='hobbies',
            field=models.CharField(max_length=300),
        ),
    ]
