# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170324_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='degree',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('mech', 'MECHANICAL')], max_length=30),
        ),
    ]
