# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_auto_20170323_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comments',
            field=models.CharField(max_length=2000),
        ),
    ]
