# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcedamicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfJoining', models.IntegerField(max_length=30)),
                ('aggregate', models.IntegerField(max_length=30)),
                ('upperSecondaryInstitution', models.CharField(max_length=70)),
                ('upperSecondaryBoard', models.CharField(max_length=30)),
                ('upperSecondaryPercentage', models.IntegerField(max_length=10)),
                ('SecondaryPercentage', models.IntegerField(max_length=10)),
                ('SecondaryInstitution', models.CharField(max_length=10)),
                ('SecondaryBoard', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coAcademicActivities', models.CharField(max_length=30)),
                ('details', models.TextField(max_length=30)),
                ('coCurriculars', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_remark', models.CharField(max_length=200)),
                ('faculty_suggestion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('notification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=70)),
                ('email', models.EmailField(max_length=30)),
                ('phoneNo', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PersonInfo'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='student_refid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PersonInfo'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PersonInfo'),
        ),
        migrations.AddField(
            model_name='acedamicinfo',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PersonInfo'),
        ),
    ]
