# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170323_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
