# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170323_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=20)),
                ('TPO_notification', models.CharField(max_length=200)),
            ],
        ),
    ]
